'use strict';
const PROPERTIES=[
{id:'aurelia',name:'The Aurelia Residence',city:'Ahmedabad · Gujarat',price:'₹4.85 Cr',priceNum:48500000,type:'residence',beds:4,baths:5,area:'4,250 sq.ft.',image:'img-aurelia',desc:'A sculptural private residence where warm stone, filtered light and generous proportions create a calm modern retreat.',amenities:['Infinity pool','Private lift','Home office','Double-height living','Smart home','Landscaped garden']},
{id:'skyline',name:'Skyline House',city:'Dubai · UAE',price:'$2.40M',priceNum:2400000,type:'villa',beds:5,baths:6,area:'5,800 sq.ft.',image:'img-skyline',desc:'A dramatic contemporary villa framed by city views, private outdoor spaces and refined hospitality-inspired interiors.',amenities:['Rooftop terrace','Pool','Cinema room','Smart home','Guest suite','City views']},
{id:'monarch',name:'Monarch Villa',city:'Goa · India',price:'₹8.20 Cr',priceNum:82000000,type:'villa',beds:5,baths:7,area:'6,100 sq.ft.',image:'img-monarch',desc:'A tropical modern estate designed around outdoor living, with mature landscaping and a private sanctuary atmosphere.',amenities:['Private pool','Garden pavilion','Outdoor kitchen','5 ensuite bedrooms','Staff room','Parking']},
{id:'nocturne',name:'Nocturne Penthouse',city:'Mumbai · Maharashtra',price:'₹12.50 Cr',priceNum:125000000,type:'penthouse',beds:4,baths:5,area:'4,900 sq.ft.',image:'img-nocturne',desc:'A rare city penthouse with panoramic views, sculptural interiors and a private entertaining terrace.',amenities:['Sky lounge','Private terrace','Concierge','Panoramic views','Private lift','Gym']},
{id:'casa',name:'Casa Verde',city:'Alibaug · Maharashtra',price:'₹6.40 Cr',priceNum:64000000,type:'villa',beds:4,baths:4,area:'3,900 sq.ft.',image:'img-casa',desc:'An understated coastal retreat with natural materials, deep verandas and effortless indoor-outdoor flow.',amenities:['Pool','Courtyard','Outdoor shower','Garden','Guest pavilion','Solar power']},
{id:'meridian',name:'Meridian Residence',city:'Bengaluru · Karnataka',price:'₹3.75 Cr',priceNum:37500000,type:'residence',beds:3,baths:4,area:'3,200 sq.ft.',image:'img-meridian',desc:'A refined urban residence balancing privacy, daylight and flexible spaces for contemporary family life.',amenities:['Club access','Study','Balcony','Security','Parking','Fitness studio']}
];
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function setupNav(){const btn=$('#menuBtn'); if(!btn)return; btn.addEventListener('click',()=>document.body.classList.toggle('nav-open'));}
function setupLoader(){const l=$('#loader'); if(!l)return; window.addEventListener('load',()=>setTimeout(()=>l.classList.add('hidden'),450));}
function setupFavorites(){ $$('.heart').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();b.classList.toggle('saved');b.textContent=b.classList.contains('saved')?'♥':'♡';})); }
function setupLeadForm(){const form=$('#leadForm');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));if(!data.name.trim()||!/^\S+@\S+\.\S+$/.test(data.email)){ $('#formNote').textContent='Please enter a valid name and email.'; return;}const leads=JSON.parse(localStorage.getItem('vanta_leads')||'[]');leads.unshift({...data,createdAt:new Date().toISOString()});localStorage.setItem('vanta_leads',JSON.stringify(leads.slice(0,100)));$('#formNote').textContent='Thank you. Your private enquiry has been received.';form.reset();});}
function renderProperties(){const grid=$('#propertyGrid');if(!grid)return;const search=$('#search'),type=$('#type'),sort=$('#sort');const draw=()=>{let a=[...PROPERTIES];const q=(search.value||'').toLowerCase().trim();if(q)a=a.filter(p=>(p.name+' '+p.city).toLowerCase().includes(q));if(type.value!=='all')a=a.filter(p=>p.type===type.value);if(sort.value==='low')a.sort((x,y)=>x.priceNum-y.priceNum);if(sort.value==='high')a.sort((x,y)=>y.priceNum-x.priceNum);grid.innerHTML=a.map(p=>card(p)).join('');$('#empty').hidden=a.length>0;setupFavorites();};[search,type,sort].forEach(x=>x&&x.addEventListener('input',draw));draw();}
function card(p){return `<article class="property-card"><a href="property.html?id=${p.id}"><div class="property-img ${p.image}"><button class="heart" data-favorite="${p.id}" aria-label="Favorite property">♡</button></div><div class="property-info"><div><h3>${p.name}</h3><p>${p.city}</p></div><strong>${p.price}</strong></div><div class="property-meta"><span>${p.beds} Beds</span><span>${p.baths} Baths</span><span>${p.area}</span></div></a></article>`;}
function renderProperty(){const root=$('#propertyDetail');if(!root)return;const id=new URLSearchParams(location.search).get('id')||'aurelia';const p=PROPERTIES.find(x=>x.id===id)||PROPERTIES[0];root.innerHTML=`<section class="property-hero ${p.image}"><div><p class="eyebrow">PRIVATE COLLECTION</p><h1>${p.name}</h1><p>${p.city} · ${p.area}</p></div></section><section class="detail section"><div class="detail-main"><p class="eyebrow dark">${p.type.toUpperCase()}</p><h2>Designed for <i>living.</i></h2><p class="lead-copy">${p.desc}</p><div class="specs"><div><b>${p.beds}</b><span>Bedrooms</span></div><div><b>${p.baths}</b><span>Bathrooms</span></div><div><b>${p.area}</b><span>Interior</span></div></div><h3>Residence features</h3><div class="amenities">${p.amenities.map(a=>`<span>✓ ${a}</span>`).join('')}</div></div><aside class="view-card" id="viewing"><span class="eyebrow dark">PRIVATE VIEWING</span><strong>${p.price}</strong><p>Arrange a personal tour with a Vanta advisor.</p><a class="btn btn-dark" href="index.html#contact">Request a viewing ↗</a></aside></section>`;}
function renderDashboard(){const table=$('#leadTable');if(!table)return;const leads=JSON.parse(localStorage.getItem('vanta_leads')||'[]');$('#leadCount').textContent=leads.length;$('#monthCount').textContent=leads.filter(x=>Date.now()-new Date(x.createdAt).getTime()<2592000000).length;table.innerHTML=leads.length?leads.map(x=>`<tr><td><b>${esc(x.name)}</b><small>${esc(x.email)}</small></td><td>${esc(x.interest)}</td><td>${esc(x.phone||'—')}</td><td>${new Date(x.createdAt).toLocaleDateString()}</td><td><span class="status">New</span></td></tr>`).join(''):`<tr><td colspan="5" class="no-leads">No enquiries yet. Submit the homepage form to populate this demo.</td></tr>`;const clear=$('#clearLeads');clear&&clear.addEventListener('click',()=>{localStorage.removeItem('vanta_leads');renderDashboard();});}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
setupNav();setupLoader();setupFavorites();setupLeadForm();renderProperties();renderProperty();renderDashboard();
